### ISSUE TITLE
Add a more... icon to know that the user should click in the text lines

### ISSUE THREAD

**Issue by turro** [mhaba/fostwom-toolkit-page#1]
Pues eso, que estaría bien un more... o un >> al final de las líneas o al principio, o donde sea, para saber que hay que clicar para que salga el texto

**Comment by mhaba** [comment]
Show more tooltip on button commit: 9be430ae5394ab2efbe2581761eda926cc73f988
Added show more button to each question/answer commit : 56eb06082584ff3e47c1b7a72ab1ff1afbe38fd0
